### ISSUE TITLE
Scrubbing backwards is not working

### ISSUE THREAD

**Issue by mwoehlke-kitware** [Kitware/vaui#25]
## Steps to reproduce:
- Scrub (or otherwise "get to") some time into the video (e.g. halfway)
- Click the scrubber knob near its current position
- Quickly drag the scrubber back to the beginning and release the mouse button

## Expected results:
Video shows first frame.

## Actual results:
A frame near the previous video position loads and the scrubber and spinner reset to that frame.

**Comment by matthewma7** [comment]
Hi @mwoehlke-kitware, thank you for filing this issue.
After we talk, it didn't take me long to find out the bug that caused the behavior. 
Thank you for noticing the bug.
Please take a look and see if the PR is good to be merged.
