### ISSUE TITLE
Scrubber doesn't work if used "too quickly"

### ISSUE THREAD

**Issue by mwoehlke-kitware** [Kitware/vaui#28]
If the user clicks on the scrubber to change to a different frame before all the background loads have completed, the scrubber and frame spinner update, but the viewer does not change to the requested frame.

**Comment by aashish24** [comment]
@mwoehlke-kitware I am closing this one if but please feel free to open it if this is still an issue.

**Comment by matthewma7** [comment]
I think this one is still true at this moment. I was thinking to fix this with the video-based player, but I start to feel maybe should fix it before that. If no one opposes, I think I'll address this in the coming weeks.

**Comment by aashish24** [comment]
thanks @matthewma7 I would think that this could be an issue for some users but obviously check on other priorities.

**Comment by matthewma7** [comment]
This is fixed in the current master branch.
