### ISSUE TITLE
Can't play video

### ISSUE THREAD

**Issue by mwoehlke-kitware** [Kitware/vaui#8]
Since #4 was merged, I can no longer play video. (Note: I don't have annotations in girder, but this should not prevent video playback. In fact, I'm dubious that playback should be prevented at all prior to annotation loading.)

**Comment by aashish24** [comment]
@matthewma7 yes we should support this use-case. I would like VAUI to display the message somewhere when it does not find annotation in a project (folder).

**Comment by aashish24** [comment]
@matthewma7 can we close this now? Also it would be useful if in the PR we can link it to the issues.

**Comment by matthewma7** [comment]
@aashish24 Yes. I'll link and close all fixed issues.

**Comment by matthewma7** [comment]
Solved with https://github.com/Kitware/vaui/pull/14
